### ISSUE TITLE
Store Netlify private hooks into .env variables

### ISSUE THREAD

**Issue by giorgioriccardi** [PulsarMedia/Gatsby-WordPress-Starter-Theme#1]
Please store your private `hook` into a `getenv()` variable in your .env cofiguration file.
I'm referring to :
https://github.com/PulsarMedia/Gatsby-WordPress-Starter-Theme/blob/master/functions.php#L82
Hope this helps

**Comment by Digital-Odyssey** [comment]
Holy crap, thanks for bringing that to my attention...i completely forgot about that. 

Thanks again.
